# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20240825-234509-icy-liqueur

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
  - name: "WhitespaceTokenizer"
  - name: "RegexFeaturizer"
  - name: "CountVectorsFeaturizer"
  - name: "CountVectorsFeaturizer"
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: "DIETClassifier"
    epochs: 10
    constrain_similarities: true

  - name: "CountVectorsFeaturizer"
    min_ngram: 1 # Consider unigrams (single words)
    max_ngram: 1 # Only unigrams

  - name: "EntitySynonymMapper"
  - name: "ResponseSelector"
    epochs: 10
    constrain_similarities: true
  - name: "FallbackClassifier"
    threshold: 0.3
    ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: "MemoizationPolicy"
  - name: "RulePolicy"
  - name: "TEDPolicy"
    max_history: 5
    epochs: 10
    constrain_similarities: true

logging:
  level: DEBUG
